default_dependencies: false
targets:
  centos-7:
    dependencies:
      - libxml2
      - libxslt
      - postgresql-devel
    before:
      - cp gemfiles/centos7.gemfile Gemfile
      - cp gemfiles/centos7.gemfile.lock Gemfile.lock
  sles-12:
    dependencies:
      - libxml2
      - libxslt
      - postgresql93
    before:
      - cp gemfiles/centos7.gemfile Gemfile
      - cp gemfiles/centos7.gemfile.lock Gemfile.lock
